# Generated by Django 4.0.3 on 2022-04-04 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_group', models.CharField(max_length=20)),
                ('group_size', models.PositiveIntegerField(default=0)),
                ('head_of_group', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_subgroup', models.CharField(max_length=20)),
                ('subgroup_size', models.PositiveIntegerField(default=0)),
                ('head_of_subgroup', models.CharField(max_length=100)),
                ('departments', models.ManyToManyField(to='HrBase.department')),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='HrBase.commoninfo')),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empl_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('date_of_employment', models.DateField()),
                ('salary', models.PositiveIntegerField(default=10000)),
                ('boss', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='HrBase.subdepartment')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='places',
            field=models.ManyToManyField(to='HrBase.places'),
        ),
    ]
